apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-platform-suite-component-wxrw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-platform-suite-component-wxrw
    app.kubernetes.io/part-of: multi-platform-suite-application-juak
  name: multi-platform-suite-component-wxrw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: multi-platform-suite-component-wxrw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: multi-platform-suite-component-wxrw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-platform-build-tenant/multi-platform-suite-application-juak/multi-platform-suite-component-wxrw@sha256:edfad9b8c80eb72047be64676359c0659886e0120d0e0e55c3d2aeae854ab862
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
